#[derive(Debug, Clone, PartialEq, Eq)]
pub(super) struct FileRequest {
    pub path: String,
    pub content: String,
}

pub(super) fn detect(request: &str) -> Option<FileRequest> {
    let path = request.split_whitespace().find_map(clean_path)?;
    Some(FileRequest {
        path,
        content: content_after_with(request),
    })
}

fn clean_path(value: &str) -> Option<String> {
    let cleaned = value.trim_matches(|ch: char| {
        matches!(
            ch,
            '"' | '\'' | '`' | ',' | ';' | ':' | '(' | ')' | '[' | ']'
        )
    });
    if cleaned.starts_with('/') || cleaned.ends_with('/') || cleaned.contains("://") {
        return None;
    }
    let has_extension = cleaned
        .rsplit_once('.')
        .is_some_and(|(_, ext)| ext.len() <= 8 && ext.chars().all(|ch| ch.is_ascii_alphanumeric()));
    let looks_file = has_extension && (cleaned.contains('/') || !cleaned.starts_with('.'));
    looks_file.then(|| cleaned.trim_start_matches("./").to_string())
}

fn content_after_with(request: &str) -> String {
    let lower = request.to_ascii_lowercase();
    if let Some(index) = lower.find(" with ") {
        return request[index + 6..].trim().to_string();
    }
    if let Some(index) = lower.find(" containing ") {
        return request[index + 12..].trim().to_string();
    }
    "Generated by AgentHub.".to_string()
}
